stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building the project..."
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  stage: test
  script:
    - echo "Running tests..."
